// Erzeugt von tools/drax_katalog_aus_preisliste.py - nicht von Hand aendern.
window.DRAX_KATALOG = {
  "stand": "2026-10-06",
  "quelle": "Drax/Preisliste 06.10.2026 (zuvor data (10).xlsx + Rechnung*.pdf)",
  "kd_nr": "11225",
  "aus_rechnungen_neu": 15,
  "aus_rechnungen_umbenannt": 3,
  "gruppen": [
    {
      "id": "weizenmehl",
      "name": "Weizenmehl & Grieß"
    },
    {
      "id": "dinkelmehl",
      "name": "Dinkelmehl & Dinkel"
    },
    {
      "id": "roggenmehl",
      "name": "Roggenmehl"
    },
    {
      "id": "backmischung",
      "name": "Backmischungen"
    },
    {
      "id": "muesli",
      "name": "Müsli & Flocken"
    },
    {
      "id": "backzutaten",
      "name": "Backzutaten"
    },
    {
      "id": "knabber",
      "name": "Knabbern & Süßes"
    },
    {
      "id": "nudeln",
      "name": "Nudeln"
    },
    {
      "id": "sonstiges",
      "name": "Sonstiges"
    }
  ],
  "artikel": [
    {
      "nr": "40401",
      "name": "Weizenmehl Type 405",
      "einheit": "1 kg",
      "ean": "4250296601351",
      "gruppe": "weizenmehl",
      "haeufigkeit": 102,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Weizenm.Type 405 1 kg"
    },
    {
      "nr": "40402",
      "name": "Weizenmehl Type 405",
      "einheit": "2,5 kg",
      "ean": "4250296601559",
      "gruppe": "weizenmehl",
      "haeufigkeit": 43,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Weizenm. 405 2,5 kg"
    },
    {
      "nr": "40405",
      "name": "Weizenmehl Type 405",
      "einheit": "5 kg",
      "ean": "4250296601566",
      "gruppe": "weizenmehl",
      "haeufigkeit": 35,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Weizenm. 405 5 kg"
    },
    {
      "nr": "40408",
      "name": "Weizenmehl 405",
      "einheit": "12,5 kg",
      "ean": "4250296601573",
      "gruppe": "weizenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Weizenm. 405 12,5 kg",
      "nicht_gelistet": true
    },
    {
      "nr": "40411",
      "name": "Weizenmehl Type 550",
      "einheit": "1 kg",
      "ean": "4250296601368",
      "gruppe": "weizenmehl",
      "haeufigkeit": 28,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Weizenm. 550 1 kg"
    },
    {
      "nr": "40412",
      "name": "Weizenmehl Type 550",
      "einheit": "2,5 kg",
      "ean": "4250296601603",
      "gruppe": "weizenmehl",
      "haeufigkeit": 46,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Weizenm. 550 2,5 kg"
    },
    {
      "nr": "40415",
      "name": "Weizenmehl Type 550",
      "einheit": "5 kg",
      "ean": "4250296601610",
      "gruppe": "weizenmehl",
      "haeufigkeit": 31,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Weizenm. 550  5 kg"
    },
    {
      "nr": "40418",
      "name": "Weizenmehl Type 550",
      "einheit": "12,5 kg",
      "ean": "4250296601627",
      "gruppe": "weizenmehl",
      "haeufigkeit": 3,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Weizenm. 550 12,5 kg"
    },
    {
      "nr": "40421",
      "name": "Weizenmehl Dunst Wiener Griessler",
      "einheit": "1 kg",
      "ean": "4250296601337",
      "gruppe": "weizenmehl",
      "haeufigkeit": 32,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Weizenm. Dun. W. Griess. 1 kg"
    },
    {
      "nr": "40432",
      "name": "Weizenmehl Type 1050",
      "einheit": "2,5 kg",
      "ean": "4250296601702",
      "gruppe": "weizenmehl",
      "haeufigkeit": 11,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Weizenm. 1050 2,5 kg"
    },
    {
      "nr": "40435",
      "name": "Weizenmehl Type 1050",
      "einheit": "5 kg",
      "ean": "4250296601719",
      "gruppe": "weizenmehl",
      "haeufigkeit": 15,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Weizenm. 1050 5 kg"
    },
    {
      "nr": "40462",
      "name": "Bio Weizenmehl Type 550",
      "einheit": "2,5 kg",
      "ean": "4250296604628",
      "gruppe": "weizenmehl",
      "haeufigkeit": 12,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Weizenm. 550 2,5 kg"
    },
    {
      "nr": "40465",
      "name": "Bio Weizenmehl Type 550",
      "einheit": "5 kg",
      "ean": "4250296604659",
      "gruppe": "weizenmehl",
      "haeufigkeit": 6,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Weizenm. 550 5 kg"
    },
    {
      "nr": "40531",
      "name": "Bio Emmermehl Type 812",
      "einheit": "1 kg",
      "ean": "4250296622004",
      "gruppe": "weizenmehl",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Emmermehl Type 812 * 1 kg"
    },
    {
      "nr": "40541",
      "name": "Bio Emmermehl Vollkorn",
      "einheit": "1 kg",
      "ean": "4250296600651",
      "gruppe": "weizenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "40550",
      "name": "Bio Hartweizengrieß",
      "einheit": "500 g",
      "ean": "4250296600743",
      "gruppe": "weizenmehl",
      "haeufigkeit": 13,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Hartweizengrieß fein 500 g"
    },
    {
      "nr": "40901",
      "name": "Bio Pizzamehl Type 00 \"Farina Alpina\"",
      "einheit": "1 kg",
      "ean": "4250296600491",
      "gruppe": "weizenmehl",
      "haeufigkeit": 33,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Pizzam. 00 \"\"Farina Alpina\"\" 1 kg"
    },
    {
      "nr": "42705",
      "name": "Bio Weizen (ganzes Korn)",
      "einheit": "5 kg",
      "ean": "4250296607049",
      "gruppe": "weizenmehl",
      "haeufigkeit": 3,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Weizen ganz. Korn 5 kg"
    },
    {
      "nr": "80515",
      "name": "Bio Dinkel (Oberkulmer Rotkorn) ganzes Korn",
      "einheit": "5 kg",
      "ean": "4250296605168",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 1,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Dinkel ganzes Korn 5 kg"
    },
    {
      "nr": "80801",
      "name": "Dinkelmehl Type 630",
      "einheit": "1 kg",
      "ean": "4250296600392",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 50,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Dinkelmehl  630 1 kg"
    },
    {
      "nr": "80802",
      "name": "Dinkelmehl Type 630",
      "einheit": "2,5 kg",
      "ean": "4250296602105",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 59,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Dinkelm. 630 2,5 kg"
    },
    {
      "nr": "80805",
      "name": "Dinkelmehl Type 630",
      "einheit": "5 kg",
      "ean": "4250296602112",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 34,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Dinkelmehl  630 5 kg"
    },
    {
      "nr": "80808",
      "name": "Dinkelmehl 630",
      "einheit": "12,5 kg",
      "ean": "4250296602129",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Dinkelm. 630 12,5 kg",
      "nicht_gelistet": true
    },
    {
      "nr": "80811",
      "name": "Dinkelmehl Dunst Wiener Griessler",
      "einheit": "1 kg",
      "ean": "4250296600378",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 27,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Din. M. Dun. W. Griess. 1 kg"
    },
    {
      "nr": "80812",
      "name": "Dinkelmehl Dunst Wiener Griessler Type 630",
      "einheit": "2,5 kg",
      "ean": "4250296602150",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 8,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Din.M. Dun. W.Griess. 630 2,5kg"
    },
    {
      "nr": "80825",
      "name": "Dinkelmehl Type 1050",
      "einheit": "5 kg",
      "ean": "4250296602211",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "80828",
      "name": "Dinkelmehl 1050",
      "einheit": "12,5 kg",
      "ean": "4250296602228",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Dinkelmehl 1050 12,5 kg",
      "nicht_gelistet": true
    },
    {
      "nr": "80850",
      "name": "Dinkelgrieß fein",
      "einheit": "500 g",
      "ean": "4250296600095",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "80872",
      "name": "Bio Dinkelmehl Dunst Wiener Griessler",
      "einheit": "2,5 kg",
      "ean": "4250296608794",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 4,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Din. Dunst W.Griess. 2,5 kg",
      "kassenname": "Bio Dinkel Dunst Wiener Griessler"
    },
    {
      "nr": "80891",
      "name": "Bio Dinkelmehl Type 630",
      "einheit": "1 kg",
      "ean": "4250296608367",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 5,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Dinkelmehl 630 1 kg"
    },
    {
      "nr": "80892",
      "name": "Bio Dinkelmehl Type 630",
      "einheit": "2,5 kg",
      "ean": "4250296608817",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 10,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Dinkelmehl 630 2,5 kg"
    },
    {
      "nr": "80895",
      "name": "Bio Dinkelmehl Type 630",
      "einheit": "5 kg",
      "ean": "4250296608824",
      "gruppe": "dinkelmehl",
      "haeufigkeit": 3,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Dinkelmehl 630 5 kg"
    },
    {
      "nr": "60601",
      "name": "Roggenmehl Type 610",
      "einheit": "1 kg",
      "ean": "4250296601030",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Roggenmehl Type 610 * 1kg"
    },
    {
      "nr": "60602",
      "name": "Roggenmehl Type 610",
      "einheit": "2,5 kg",
      "ean": "4250296601856",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Roggenmehl Type 610 * 2,5kg"
    },
    {
      "nr": "60605",
      "name": "Roggenmehl Type 610",
      "einheit": "5 kg",
      "ean": "4250296601863",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "60611",
      "name": "Roggenmehl Type 997",
      "einheit": "1 kg",
      "ean": "4250296601047",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "60612",
      "name": "Roggenmehl Type 997",
      "einheit": "2,5 kg",
      "ean": "4250296601900",
      "gruppe": "roggenmehl",
      "haeufigkeit": 7,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Roggenm.  997 2,5kg"
    },
    {
      "nr": "60615",
      "name": "Roggenmehl Type 997",
      "einheit": "5 kg",
      "ean": "4250296601917",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "60641",
      "name": "Bio Roggenmehl Type 1370",
      "einheit": "1 kg",
      "ean": "4250296606417",
      "gruppe": "roggenmehl",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "55521",
      "name": "Bio Dinkel Zitronen-Backmischung",
      "einheit": "590 g",
      "ean": "4250296605212",
      "gruppe": "backmischung",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Bio Dinkel Zitr. B.misch. 590 g",
      "nicht_gelistet": true
    },
    {
      "nr": "55600",
      "name": "Bio Kartoffelbrot-Mischung",
      "einheit": "1 kg",
      "ean": "4250296656009",
      "gruppe": "backmischung",
      "haeufigkeit": 2,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Kartoffelbr. Misch. 1 kg"
    },
    {
      "nr": "55610",
      "name": "Bio Bauernbrot Brotbackmischung",
      "einheit": "1 kg",
      "ean": "4250296656108",
      "gruppe": "backmischung",
      "haeufigkeit": 3,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Bauernb. Backm. 1 kg"
    },
    {
      "nr": "55623",
      "name": "Bio 3-Saaten Mischung",
      "einheit": "350 g",
      "ean": "4250296656238",
      "gruppe": "backmischung",
      "haeufigkeit": 12,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio 3-Saten Misch. 500 g"
    },
    {
      "nr": "55630",
      "name": "Bio Partybrot Brotbackmischung",
      "einheit": "1 kg",
      "ean": "4250296656306",
      "gruppe": "backmischung",
      "haeufigkeit": 2,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Partybrot Misch: 1 kg"
    },
    {
      "nr": "55640",
      "name": "Bio Hildegard Energie-Kekse Dinkelbackmischung",
      "einheit": "350 g",
      "ean": "4250296656405",
      "gruppe": "backmischung",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "55645",
      "name": "Bio Weizen-Pizza Backmischung",
      "einheit": "700 g",
      "ean": "4250296656450",
      "gruppe": "backmischung",
      "haeufigkeit": 10,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Weizen-Pizza Misch.700 g",
      "kassenname": "Bio Weizen-Pizza-Mischung"
    },
    {
      "nr": "55685",
      "name": "Bio Kerndlbrot-Mischung",
      "einheit": "1 kg",
      "ean": "4250296656856",
      "gruppe": "backmischung",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Bio Kerndlbr. Misch. 1 kg",
      "nicht_gelistet": true
    },
    {
      "nr": "38050",
      "name": "Frühstücksbrei \"Porridge\" Basis",
      "einheit": "500 g",
      "ean": "4006040014072",
      "gruppe": "muesli",
      "haeufigkeit": 5,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Frühstücksbrei Basis"
    },
    {
      "nr": "55740",
      "name": "Bio Hafer-Porridgeflocken fein",
      "einheit": "500 g",
      "ean": "4250296655545",
      "gruppe": "muesli",
      "haeufigkeit": 13,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Hafer-Porridgefl. fein 500 g"
    },
    {
      "nr": "78586",
      "name": "Bio Dinkel gepufft natur",
      "einheit": "200 g",
      "ean": "4002543001281",
      "gruppe": "muesli",
      "haeufigkeit": 10,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Dinkel gepufft natur"
    },
    {
      "nr": "78590",
      "name": "Bio Hirse gepufft natur",
      "einheit": "200 g",
      "ean": "4002543225069",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Hirse gepufft natur"
    },
    {
      "nr": "88004",
      "name": "Bio Erdbeer Cluster Crunchy",
      "einheit": "375 g",
      "ean": "4250296611046",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "Bio Erdbeer Cluster Crunchy"
    },
    {
      "nr": "88005",
      "name": "Bio Honig-Dinkel gepufft",
      "einheit": "200 g",
      "ean": "4250296611022",
      "gruppe": "muesli",
      "haeufigkeit": 11,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Honig-Dinkel gepufft"
    },
    {
      "nr": "88006",
      "name": "Bio Amaranth Beerenmüsli",
      "einheit": "500 g",
      "ean": "4250296611060",
      "gruppe": "muesli",
      "haeufigkeit": 9,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Amaranth Beerenmüsli"
    },
    {
      "nr": "88020",
      "name": "Bio Haferflocken Kleinblatt",
      "einheit": "500 g",
      "ean": "4250296611206",
      "gruppe": "muesli",
      "haeufigkeit": 46,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Haferfl. Kleinblatt 500g"
    },
    {
      "nr": "88032",
      "name": "Amaranth-Schokomüsli",
      "einheit": "500 g",
      "ean": "4250296680325",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Amaranth-Schokomüsli"
    },
    {
      "nr": "88034",
      "name": "Schoko Knusper Müsli",
      "einheit": "1 kg",
      "ean": "4250296680349",
      "gruppe": "muesli",
      "haeufigkeit": 44,
      "lieferungen": 3,
      "aktiv": true,
      "quelle": "DRX Schoko Knusper Müsli 1kg"
    },
    {
      "nr": "88035",
      "name": "Müsli Schoko Knusper",
      "einheit": "500 g",
      "ean": "4250296680356",
      "gruppe": "muesli",
      "haeufigkeit": 32,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Schoko Knusper Müsli 500g"
    },
    {
      "nr": "88047",
      "name": "Bio Grundmischung",
      "einheit": "1 kg",
      "ean": "4250296680479",
      "gruppe": "muesli",
      "haeufigkeit": 15,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Grundmischung 1kg"
    },
    {
      "nr": "88055",
      "name": "Bio Früchtemüsli",
      "einheit": "1 kg",
      "ean": "4250296680554",
      "gruppe": "muesli",
      "haeufigkeit": 11,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Früchtemüsli 1kg"
    },
    {
      "nr": "88057",
      "name": "Schoko-Dinkelmüsli",
      "einheit": "500 g",
      "ean": "4250296680578",
      "gruppe": "muesli",
      "haeufigkeit": 17,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Schoko-Dinkelmüsli"
    },
    {
      "nr": "88060",
      "name": "Schoko-Dinkel gepufft",
      "einheit": "200 g",
      "ean": "4250296680608",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Schoko-Dinkel gepufft"
    },
    {
      "nr": "88061",
      "name": "Bio Amaranth gepufft",
      "einheit": "200 g",
      "ean": "4250296680615",
      "gruppe": "muesli",
      "haeufigkeit": 8,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Amaranth gepufft"
    },
    {
      "nr": "88063",
      "name": "Dinkel-Frucht-Müsli mit gepufftem Dinkel",
      "einheit": "500 g",
      "ean": "4250296680639",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Dinkel-Frucht-Müsli mit gepufftem Dinkel"
    },
    {
      "nr": "88064",
      "name": "Dinkel-Knusper-Müsli",
      "einheit": "500 g",
      "ean": "4250296680646",
      "gruppe": "muesli",
      "haeufigkeit": 16,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Dinkel-Knusper-Müsli"
    },
    {
      "nr": "88070",
      "name": "Cornflakes",
      "einheit": "250 g",
      "ean": "4250296680707",
      "gruppe": "muesli",
      "haeufigkeit": 43,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Cornflakes 250g"
    },
    {
      "nr": "88232",
      "name": "Bio Hafer Cluster Crunchy",
      "einheit": "375 g",
      "ean": "4250296682329",
      "gruppe": "muesli",
      "haeufigkeit": 38,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Bio Hafer Cluster Crunchy"
    },
    {
      "nr": "88253",
      "name": "Bio Amaranth Früchtemüsli",
      "einheit": "500 g",
      "ean": "4250966110534",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Amaranth Früchtemüsli"
    },
    {
      "nr": "88812",
      "name": "Bio Haferflocken Großblatt",
      "einheit": "1 kg",
      "ean": "4250296611008",
      "gruppe": "muesli",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Haferflocken Großblatt 1kg"
    },
    {
      "nr": "88949",
      "name": "Bio Haferflocken Kleinblatt",
      "einheit": "1 kg",
      "ean": "4250296689496",
      "gruppe": "muesli",
      "haeufigkeit": 76,
      "lieferungen": 4,
      "aktiv": true,
      "quelle": "DRX Bio Haferfl. Kleinblatt 1kg"
    },
    {
      "nr": "11024",
      "name": "Vanillezucker Lecker's",
      "einheit": "",
      "ean": "4013044110020",
      "gruppe": "backzutaten",
      "haeufigkeit": 26,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Vanillezucker Lecker`s"
    },
    {
      "nr": "45020",
      "name": "Bio Gerstenmalzmehl (aktiv)",
      "einheit": "250 g",
      "ean": "4250296600682",
      "gruppe": "backzutaten",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Gerstenmalzmehl * 250 g (aktiv)"
    },
    {
      "nr": "88082",
      "name": "Sonnenblumenkerne",
      "einheit": "500 g",
      "ean": "4250296680820",
      "gruppe": "backzutaten",
      "haeufigkeit": 11,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Sonnenblumenkerne 500g"
    },
    {
      "nr": "88126",
      "name": "Kürbiskerne",
      "einheit": "250 g",
      "ean": "4250296681261",
      "gruppe": "backzutaten",
      "haeufigkeit": 17,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Kürbiskerne 250g"
    },
    {
      "nr": "88130",
      "name": "Brotgewürz fein",
      "einheit": "150 g",
      "ean": "4250296681308",
      "gruppe": "backzutaten",
      "haeufigkeit": 13,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Brotgewürz fein * 150g"
    },
    {
      "nr": "88133",
      "name": "Roggenvollkorn Sauerteig",
      "einheit": "250 g",
      "ean": "4250296681339",
      "gruppe": "backzutaten",
      "haeufigkeit": 9,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Rogg.vollk. Sauert.250 g"
    },
    {
      "nr": "88134",
      "name": "Trockenhefe - Instant",
      "einheit": "8x11g",
      "ean": "4250296681346",
      "gruppe": "backzutaten",
      "haeufigkeit": 14,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Instant-Trockenhefe"
    },
    {
      "nr": "88135",
      "name": "Vanillezucker Bourbon konv.",
      "einheit": "200 g",
      "ean": "4250296681353",
      "gruppe": "backzutaten",
      "haeufigkeit": 19,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Vanillezucker Bourbon konv.",
      "kassenname": "Vanillezucker Bourbon konventionell"
    },
    {
      "nr": "88214",
      "name": "Bio Dinkel Backerbsen",
      "einheit": "125 g",
      "ean": "4250296682145",
      "gruppe": "backzutaten",
      "haeufigkeit": 34,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Dinkel Backerbsen"
    },
    {
      "nr": "88512",
      "name": "Bio Chia Samen",
      "einheit": "200 g",
      "ean": "4250296691123",
      "gruppe": "backzutaten",
      "haeufigkeit": 15,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Chia Samen 200 g"
    },
    {
      "nr": "88099",
      "name": "Erdbeer-Knusperwaffeln in weißer Joghurtschokolade",
      "einheit": "150 g",
      "ean": "4250296680998",
      "gruppe": "knabber",
      "haeufigkeit": 7,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Erdb-Knus.waf. Jogh.schoko."
    },
    {
      "nr": "88139",
      "name": "Bio Dinkel Cräcker Parmesan",
      "einheit": "100 g",
      "ean": "4250296681391",
      "gruppe": "knabber",
      "haeufigkeit": 2,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Dinkel Cräcker Parme."
    },
    {
      "nr": "88141",
      "name": "Bio Dinkel Cräcker Tomate",
      "einheit": "100 g",
      "ean": "4250296681414",
      "gruppe": "knabber",
      "haeufigkeit": 5,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Dinkel Cräcker Tomate"
    },
    {
      "nr": "88155",
      "name": "Bio Dinkel Orangen Keks",
      "einheit": "200 g",
      "ean": "4250296681551",
      "gruppe": "knabber",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Bio Dinkel Orangen Keks"
    },
    {
      "nr": "88184",
      "name": "Joghurt-Schoko-Kugeln",
      "einheit": "",
      "ean": "4250296681841",
      "gruppe": "knabber",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": false,
      "quelle": "DRX Joghurt-Schoko-Kugeln",
      "nicht_gelistet": true
    },
    {
      "nr": "88187",
      "name": "Schoko-Vollmilch Apfelscheiben",
      "einheit": "125 g",
      "ean": "4250296681872",
      "gruppe": "knabber",
      "haeufigkeit": 3,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Schoko-VM Apfelscheiben"
    },
    {
      "nr": "88191",
      "name": "Vanille-Schoko-Mandeln",
      "einheit": "150 g",
      "ean": "4250296681919",
      "gruppe": "knabber",
      "haeufigkeit": 12,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Vanille-Schoko-Mandeln"
    },
    {
      "nr": "88192",
      "name": "Zimt-Schoko-Kugeln",
      "einheit": "200 g",
      "ean": "4250296681926",
      "gruppe": "knabber",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Zimt-Schoko-Kugeln"
    },
    {
      "nr": "88196",
      "name": "Schoko-Apfelscheiben gemischt",
      "einheit": "125 g",
      "ean": "4250296681964",
      "gruppe": "knabber",
      "haeufigkeit": 13,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Schoko-Apfelsch. misch."
    },
    {
      "nr": "88208",
      "name": "Zartbitter Cranberries",
      "einheit": "125 g",
      "ean": "4250296682084",
      "gruppe": "knabber",
      "haeufigkeit": 11,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Zartbitter Cranberries"
    },
    {
      "nr": "88240",
      "name": "Dinkel-Waffelröllchen Bio natur",
      "einheit": "100 g",
      "ean": "4250296682404",
      "gruppe": "knabber",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Dinkel-Waffelröllchen Bio natur"
    },
    {
      "nr": "88401",
      "name": "Vollmilch Reiswaffeln",
      "einheit": "150 g",
      "ean": "4250296671422",
      "gruppe": "knabber",
      "haeufigkeit": 31,
      "lieferungen": 2,
      "aktiv": true,
      "quelle": "DRX Vollmilch Reiswaffeln"
    },
    {
      "nr": "88402",
      "name": "Zartbitter Reiswaffeln",
      "einheit": "150 g",
      "ean": "4250296671590",
      "gruppe": "knabber",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "Zartbitter Reiswaffeln * 150 g"
    },
    {
      "nr": "88411",
      "name": "Dinkel Vollmilch Knusperwaffeln",
      "einheit": "150 g",
      "ean": "4250296671965",
      "gruppe": "knabber",
      "haeufigkeit": 16,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Dinkel VM Knusperwaffeln"
    },
    {
      "nr": "88412",
      "name": "Dinkel Vollmilch-Mandelsplitter Knusperwaffeln",
      "einheit": "150 g",
      "ean": "4250296672139",
      "gruppe": "knabber",
      "haeufigkeit": 19,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Din. VM Mand.splitter K.waf."
    },
    {
      "nr": "88413",
      "name": "Dinkel Zartbitter Knusperwaffeln",
      "einheit": "150 g",
      "ean": "4250296672436",
      "gruppe": "knabber",
      "haeufigkeit": 13,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Din. Zartb.Knusperwaffeln"
    },
    {
      "nr": "65948",
      "name": "Bandnudeln 8mm",
      "einheit": "500 g",
      "ean": "4002861404122",
      "gruppe": "nudeln",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "65954",
      "name": "Hörnchen",
      "einheit": "",
      "ean": "4002861404184",
      "gruppe": "nudeln",
      "haeufigkeit": 8,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Hörnchen"
    },
    {
      "nr": "65955",
      "name": "Spiralen",
      "einheit": "",
      "ean": "4002861404214",
      "gruppe": "nudeln",
      "haeufigkeit": 2,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Spiralen"
    },
    {
      "nr": "65960",
      "name": "Spaghetti",
      "einheit": "500 g",
      "ean": "4002861404290",
      "gruppe": "nudeln",
      "haeufigkeit": 5,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Spaghetti 500 g"
    },
    {
      "nr": "10045",
      "name": "Reinweinstein Backpulver",
      "einheit": "4x21g",
      "ean": "4013044100007",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "11263",
      "name": "Ur-Salz fein",
      "einheit": "12 kg",
      "ean": "4000345020387",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Ur-Salz fein 12kg"
    },
    {
      "nr": "11634",
      "name": "Krunchy Himbeere",
      "einheit": "500 g",
      "ean": "4021234101581",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "29487",
      "name": "Bio Sesam ungeschält",
      "einheit": "250 g",
      "ean": "4019339419069",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "36577",
      "name": "Dinkel Backerbsen",
      "einheit": "100 g",
      "ean": "4033425307016",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "36851",
      "name": "Brotgewürz ganz",
      "einheit": "500 g",
      "ean": "4250296620505",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "38255",
      "name": "Klare Suppe ohne Hefe",
      "einheit": "500 g",
      "ean": "4006040271130",
      "gruppe": "sonstiges",
      "haeufigkeit": 18,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Klare Suppe ohne Hefe"
    },
    {
      "nr": "44801",
      "name": "\"Bio Sonntagsmehl für Kuchen und Gebäck\"",
      "einheit": "1 kg",
      "ean": "4250296684521",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "45661",
      "name": "Bio Rotkornweizen Vollkornmehl",
      "einheit": "1 kg",
      "ean": "4250296605267",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "55705",
      "name": "Bio Focaccia Brotbackmischung",
      "einheit": "500 g",
      "ean": "4250296657051",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "55741",
      "name": "Bio Hafer-Porridgeflocken fein",
      "einheit": "1 kg",
      "ean": "4250296656849",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "78549",
      "name": "Klare Delikatess-Suppe \"Frei von\"",
      "einheit": "540 g",
      "ean": "4009831022119",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Tellofix 540 g / 27 l"
    },
    {
      "nr": "82900",
      "name": "Bio Braunhirse gemahlen",
      "einheit": "500 g",
      "ean": "4250296608916",
      "gruppe": "sonstiges",
      "haeufigkeit": 16,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "DRX Bio Braunhirse gemal. 500 g"
    },
    {
      "nr": "82901",
      "name": "Bio Braunhirse gemahlen",
      "einheit": "1 kg",
      "ean": "4250296608909",
      "gruppe": "sonstiges",
      "haeufigkeit": 16,
      "lieferungen": 1,
      "aktiv": true,
      "quelle": "DRX Bio Braunhirse gemal. 1 kg"
    },
    {
      "nr": "84301",
      "name": "Bio Einkornmehl Vollkorn",
      "einheit": "1 kg",
      "ean": "4250296604468",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88041",
      "name": "Familienmüsli",
      "einheit": "2 kg",
      "ean": "4250296680417",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88078",
      "name": "Schoko-Cornflakes",
      "einheit": "250 g",
      "ean": "4250296680783",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88125",
      "name": "Kürbiskerne",
      "einheit": "1 kg",
      "ean": "4250296681254",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88410",
      "name": "Dinkel Vollmilch-Cornflakes Knusperwaffeln",
      "einheit": "150 g",
      "ean": "4250296671842",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88420",
      "name": "Dinkel Zartbitter-Mandelsplitter Knusperwaffeln",
      "einheit": "150 g",
      "ean": "4250296674317",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    },
    {
      "nr": "88452",
      "name": "Vollmilch Reistaler mit Schokofuss",
      "einheit": "100 g",
      "ean": "4250296680394",
      "gruppe": "sonstiges",
      "haeufigkeit": 0,
      "lieferungen": 0,
      "aktiv": true,
      "quelle": "Preisliste"
    }
  ]
};
